[package]
name = "ezhttp"
entry = "ezhttp/main.bend"

[deps.ezjson]
hash = "0x81c67699424929b5c44cd8577e18117f"
git = "https://github.com/Emerging-Patterns/ezjson"
rev = "f35ea6ce89962d338cdc0735cc7724ed82d47594"
tag = "v1.1.0"
root = "."
narHash = "sha256-yHxl1aW4luf2bdPqOUcULhOEZLlcaTOWjTrPJys4CMI="
entry = "main.bend"
